name: deploy-synthetics-branch

on:
  push:
    branches-ignore:
      - main
      - master
    paths:
      - .github/workflows/deploy-synthetics-branch.yaml
      - cloudformation/synthetics-*

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        run: yamllint -c ./.github/linters/.yaml-lint.yaml .github/ cloudformation/
